// Lane: P3 frontend
import type { Alert, Decision, LineageLink } from "@/lib/api";

export const mockDecisions: Decision[] = [
  {
    id: "dec-001",
    summary: "Use JWT for auth instead of server sessions",
    date: "Jan 14, 2026",
    participants: ["@alice", "@bob"],
    source: "Slack",
    rationale: "Stateless auth works better for mobile clients.",
    alternatives_rejected: ["Server sessions"],
  },
  {
    id: "dec-002",
    summary: "Keep checkout to three steps",
    date: "Feb 28, 2026",
    participants: ["@design-lead"],
    source: "Notion",
    rationale: "A short, predictable flow reduces abandonment.",
    alternatives_rejected: ["Single-page checkout", "Five-step checkout"],
  },
  {
    id: "dec-003",
    summary: "Use Postgres as the system of record",
    date: "Feb 3, 2026",
    participants: ["@priya", "@raj"],
    source: "Slack",
    rationale: "Relational integrity matters for billing and audits.",
    alternatives_rejected: ["MongoDB"],
  },
  {
    id: "dec-004",
    summary: "Send billing events through the audit queue",
    date: "Mar 8, 2026",
    participants: ["@marco", "@alice"],
    source: "GitHub",
    rationale: "Billing changes need replayable audit events for compliance.",
    alternatives_rejected: ["Direct writes from webhook handlers"],
  },
  {
    id: "dec-005",
    summary: "Keep plan limits enforced server-side",
    date: "Mar 21, 2026",
    participants: ["@sam", "@nora"],
    source: "Notion",
    rationale: "Client-side checks are useful for UX but cannot be trusted.",
    alternatives_rejected: ["Frontend-only enforcement"],
  },
  {
    id: "dec-006",
    summary: "Prefer REST endpoints for partner integrations",
    date: "Apr 2, 2026",
    participants: ["@raj", "@mika"],
    source: "Slack",
    rationale: "Partners asked for predictable endpoints and simpler auth flows.",
    alternatives_rejected: ["GraphQL for partner APIs"],
  },
  {
    id: "dec-007",
    summary: "Store decision provenance with every policy change",
    date: "Apr 19, 2026",
    participants: ["@alice", "@design-lead"],
    source: "Notion",
    rationale: "Future reviewers need to know why a rule exists before changing it.",
    alternatives_rejected: ["Policy rows without linked decisions"],
  },
  {
    id: "dec-008",
    summary: "Use feature flags for risky rollout paths",
    date: "May 4, 2026",
    participants: ["@bob", "@sam"],
    source: "GitHub",
    rationale: "Flags let the team reverse risky changes without emergency deploys.",
    alternatives_rejected: ["All-or-nothing deploys"],
  },
  {
    id: "dec-009",
    summary: "Require webhook handlers to acknowledge quickly",
    date: "May 17, 2026",
    participants: ["@priya", "@nora"],
    source: "Slack",
    rationale: "Third-party platforms retry aggressively when handlers take too long.",
    alternatives_rejected: ["Blocking webhook handlers"],
  },
  {
    id: "dec-010",
    summary: "Show active contradictions in the dashboard",
    date: "May 31, 2026",
    participants: ["@mika", "@marco"],
    source: "Notion",
    rationale: "The UI should make the live agent visible during demos and reviews.",
    alternatives_rejected: ["GitHub-only contradiction feedback"],
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "alert-001",
    decision_id: "dec-001",
    severity: "structural",
    source: "GitHub",
    source_ref: "trisolarans/covenant-demo@001",
    message: "New auth code introduces sessions despite the JWT decision.",
    status: "open",
    created_at: "2026-06-06T10:00:00.000Z",
    decision: mockDecisions[0],
  },
];

export const mockLineage: LineageLink[] = [
  {
    id: "lineage-001",
    decision_id: "dec-001",
    type: "Code",
    label: "Auth middleware",
    target: "src/auth/middleware.ts:1-87",
    source: "GitHub",
    note: "Validates JWT bearer tokens before protected route access.",
  },
  {
    id: "lineage-002",
    decision_id: "dec-001",
    type: "Spec",
    label: "Mobile login notes",
    target: "notion://decision-ledger/jwt-auth",
    source: "Notion",
    note: "Documents why mobile clients should not depend on server sessions.",
  },
  {
    id: "lineage-003",
    decision_id: "dec-001",
    type: "Test",
    label: "Auth regression tests",
    target: "tests/auth/session_regression.test.ts:12-62",
    source: "GitHub",
    note: "Catches session-based auth regressions before review.",
  },
  {
    id: "lineage-004",
    decision_id: "dec-002",
    type: "Design",
    label: "Checkout flow spec",
    target: "figma://checkout-v4/flow",
    source: "Notion",
    note: "Three-step sequence used by web and mobile checkout.",
  },
  {
    id: "lineage-005",
    decision_id: "dec-003",
    type: "Schema",
    label: "Billing schema",
    target: "db/schema/billing.sql:1-144",
    source: "GitHub",
    note: "Relational billing tables inherit the Postgres decision.",
  },
];
